/**
 * wiretype codegen — naming & endpoint-key helpers.
 *
 * Pure, dependency-free helpers shared by all emitters. No runtime import
 * from wiretype core (types only) so this compiles/tests before core exists.
 */

import type { ApiModel, Endpoint } from '../core/index.js';

/** The default header banner prepended to every generated file. */
export const DEFAULT_BANNER = 'Generated by wiretype — do not edit.';

/** Build a `//`-style banner comment block from a banner string. */
export function bannerComment(banner: string): string {
  return `// ${banner}\n`;
}

/**
 * Stable "METHOD /pattern" key used by the ApiEndpoints map, MSW comments,
 * and human-facing labels. e.g. `GET /api/users/:userId`.
 */
export function endpointKey(ep: Endpoint): string {
  return `${ep.method.toUpperCase()} ${ep.pattern}`;
}

/**
 * Choose the "success" response variant for an endpoint: lowest 2xx status,
 * otherwise the lowest status overall. Responses are already sorted ascending
 * by core, but we do not rely on that here.
 */
export function pickSuccessStatus(ep: Endpoint): number {
  const statuses = ep.responses.map((r) => r.status);
  const twoxx = statuses.filter((s) => s >= 200 && s < 300).sort((a, b) => a - b);
  if (twoxx.length > 0) return twoxx[0]!;
  return [...statuses].sort((a, b) => a - b)[0]!;
}

/**
 * Suffix appended to a response type/schema name for a given status. The
 * success status gets no suffix; every other status gets its numeric suffix.
 */
export function responseSuffix(ep: Endpoint, status: number): string {
  return status === pickSuccessStatus(ep) ? '' : String(status);
}

/** Endpoints in deterministic model order (as provided by core). */
export function orderedEndpoints(model: ApiModel): Endpoint[] {
  return model.endpoints;
}

/** Indentation helper: `n` levels of two spaces. */
export function pad(indent: number): string {
  return '  '.repeat(Math.max(0, indent));
}

/**
 * Is `key` a valid bare TS/JS identifier usable as an unquoted object key /
 * interface member? If not, callers should quote it.
 */
export function isSafeIdentifier(key: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);
}

/** Quote an object key only when it is not a safe bare identifier. */
export function propKey(key: string): string {
  return isSafeIdentifier(key) ? key : JSON.stringify(key);
}
