/**
 * wiretype codegen — public option & result types.
 */

export interface CodegenOptions {
  /** Header comment banner. Default: "Generated by wiretype — do not edit." */
  banner?: string;
  /** Base URL used in MSW handlers. Default: "*" (match any origin) + pattern. */
  mswBaseUrl?: string;
  /**
   * When true, `handlers.ts` imports each mock body from
   * `./fixtures/<operationId>.<status>.json` instead of inlining it, and
   * `generateAll` emits those fixture files alongside it. Default false.
   */
  mswFixtures?: boolean;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

/** Codegen targets. */
export type CodegenTarget = 'ts' | 'zod' | 'msw' | 'openapi' | 'model';
