/**
 * wiretype codegen — public option & result types.
 */

export interface CodegenOptions {
  /** Header comment banner. Default: "Generated by wiretype — do not edit." */
  banner?: string;
  /** Base URL used in MSW handlers. Default: "*" (match any origin) + pattern. */
  mswBaseUrl?: string;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

/** Codegen targets. */
export type CodegenTarget = 'ts' | 'zod' | 'msw' | 'openapi' | 'model';
